package com.mobilebook.model.bc.vo;

import com.mobilebook.model.bc.vo.common.CheckInDataViewRow;

import java.sql.Timestamp;

import java.util.Date;

import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 09 20:35:17 CEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CheckInDataViewRowImpl extends ViewRowImpl implements CheckInDataViewRow {

    public static final int ENTITY_CHECKINDATA = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        FirstName,
        LastName,
        FlightNo,
        Identification,
        HasCheckInLuggage,
        CheckedInOn,
        IdNumber,
        FlightsView;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int FLIGHTNO = AttributesEnum.FlightNo.index();
    public static final int IDENTIFICATION = AttributesEnum.Identification.index();
    public static final int HASCHECKINLUGGAGE = AttributesEnum.HasCheckInLuggage.index();
    public static final int CHECKEDINON = AttributesEnum.CheckedInOn.index();
    public static final int IDNUMBER = AttributesEnum.IdNumber.index();
    public static final int FLIGHTSVIEW = AttributesEnum.FlightsView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CheckInDataViewRowImpl() {
    }
    
    public void makeCheckIn(String hasCheckInLuggage){
        setCheckedInOn(new Timestamp(new Date().getTime()));
        setHasCheckInLuggage(hasCheckInLuggage);
        getApplicationModule().getTransaction().commit();
    }
    
    public void makeCheckInUser(){
        makeCheckIn("N");
    }

    /**
     * Gets CheckInData entity object.
     * @return the CheckInData
     */
    public EntityImpl getCheckInData() {
        return (EntityImpl) getEntity(ENTITY_CHECKINDATA);
    }

    /**
     * Gets the attribute value for FIRST_NAME using the alias name FirstName.
     * @return the FIRST_NAME
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName.
     * @param value value to set the FIRST_NAME
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for LAST_NAME using the alias name LastName.
     * @return the LAST_NAME
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName.
     * @param value value to set the LAST_NAME
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for FLIGHT_NO using the alias name FlightNo.
     * @return the FLIGHT_NO
     */
    public String getFlightNo() {
        return (String) getAttributeInternal(FLIGHTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for FLIGHT_NO using the alias name FlightNo.
     * @param value value to set the FLIGHT_NO
     */
    public void setFlightNo(String value) {
        setAttributeInternal(FLIGHTNO, value);
    }

    /**
     * Gets the attribute value for IDENTIFICATION using the alias name Identification.
     * @return the IDENTIFICATION
     */
    public String getIdentification() {
        return (String) getAttributeInternal(IDENTIFICATION);
    }

    /**
     * Sets <code>value</code> as attribute value for IDENTIFICATION using the alias name Identification.
     * @param value value to set the IDENTIFICATION
     */
    public void setIdentification(String value) {
        setAttributeInternal(IDENTIFICATION, value);
    }

    /**
     * Gets the attribute value for HAS_CHECK_IN_LUGGAGE using the alias name HasCheckInLuggage.
     * @return the HAS_CHECK_IN_LUGGAGE
     */
    public String getHasCheckInLuggage() {
        return (String) getAttributeInternal(HASCHECKINLUGGAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for HAS_CHECK_IN_LUGGAGE using the alias name HasCheckInLuggage.
     * @param value value to set the HAS_CHECK_IN_LUGGAGE
     */
    public void setHasCheckInLuggage(String value) {
        setAttributeInternal(HASCHECKINLUGGAGE, value);
    }

    /**
     * Gets the attribute value for CHECKED_IN_ON using the alias name CheckedInOn.
     * @return the CHECKED_IN_ON
     */
    public Timestamp getCheckedInOn() {
        return (Timestamp) getAttributeInternal(CHECKEDINON);
    }

    /**
     * Sets <code>value</code> as attribute value for CHECKED_IN_ON using the alias name CheckedInOn.
     * @param value value to set the CHECKED_IN_ON
     */
    public void setCheckedInOn(Timestamp value) {
        setAttributeInternal(CHECKEDINON, value);
    }

    /**
     * Gets the attribute value for ID_NUMBER using the alias name IdNumber.
     * @return the ID_NUMBER
     */
    public String getIdNumber() {
        return (String) getAttributeInternal(IDNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for ID_NUMBER using the alias name IdNumber.
     * @param value value to set the ID_NUMBER
     */
    public void setIdNumber(String value) {
        setAttributeInternal(IDNUMBER, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link FlightsView.
     */
    public RowIterator getFlightsView() {
        return (RowIterator) getAttributeInternal(FLIGHTSVIEW);
    }
}

