package com.mobilebook.model.bc.vo.common;

import java.util.Date;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 09 20:45:11 CEST 2018
// ---------------------------------------------------------------------
public interface FlightsViewRow extends Row {
    void updateFlightDate(Date flightDate);
}

